export const GET_REVIEWS_ATTEMPT = 'GET_REVIEWS_ATTEMPT';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const POST_REVIEW_ATTEMPT = 'POST_REVIEW_ATTEMPT';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';